### ISSUE TITLE
Implement callback example

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-android-sdk#21]
## Description

Implement an example of function which has callback function.

* https://github.com/jni-rs/jni-rs/blob/master/example/HelloWorld.java#L24
* https://github.com/jni-rs/jni-rs/blob/master/example/mylib/src/lib.rs#L65

### Purpose

We wanna call "Library layer" written by Kotlin from "rust layer" to use android native database.

**Comment by omuomugin** [comment]
[Memo]
I'm guessing there are 2 ways to implement this.

1. Passing object to Rust Layer (links in description is this way)
In this way Rust have to call method and need to do some research on 
- Is object alive forever?
- Method should be almost like reflection. Since there are no linking from Rust to Java (this maybe not true)

2. Try to poll and get callback when needed.
In this way Java is the one who is calling the method, so don't have to worry about reflection and other lifecycle of object.
- How often should we poll?
- Are there any performance issue?

Continue researching these issue.

**Comment by omuomugin** [comment]
JNI docs are  here
https://docs.rs/jni/0.9.3/jni/struct.JNIEnv.html

**Comment by syuhei176** [comment]
One of scenario is EventWatcher(on Kotlin?) receive "deposit event" from Ethereum. Basically EventWatcher poll Ethereum node every 15 seconds. EventWatcher calls StateManager.applyState(actually through SyncManager) and StateManager calls database on Kotlin.
<img width="810" alt="Screen Shot 2019-07-22 at 1 24 25" src="https://user-images.githubusercontent.com/1094660/61593823-819ca080-ac1f-11e9-824f-b89884aea7f6.png">

**Comment by omuomugin** [comment]
Ok, so in my opinion, the easiest way is solution 1 which passes the Object.
But safest way is polling and subscribing some kind of State Manager.

I'm implementing experimental program right now in #23 
I'll be some drawing to tell image of polling soon.
